[package]
name = "ardos-ui"
version = "0.1.0"
edition = "2024"
[workspace]
members = ["ardos-ui-rsml-compiler"]
[dependencies]
skia-safe = { version = "0.86.0", features = ["gl"] }
color-eyre = "0.6.3"
winit = { git = "https://github.com/SergioRibera/winit/", branch = "layer_shell", version = "0.31.0-beta.2"}
glutin = { git = "https://github.com/coffeeispower/glutin", version = "0.32.3" }
glutin-winit = { git = "https://github.com/coffeeispower/glutin", version = "0.5.0" }
log = "0.4.27"
ardos-ui-rsml-compiler = { path = "ardos-ui-rsml-compiler" }
uuid = { version = "1.18.1", features = ["v4"] }
[dependencies.clay-layout]
features = ["debug"]
git = "https://github.com/coffeeispower/clay-rs"
#branch = "tibs-version"
rev = "59f2f5a607dac5df2fd7cd8dda7fb49ddd910c4f"

[dev-dependencies]
env_logger = "0.11.8"
